name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # heroku deployment
      - uses: actions/checkout@v2
      - name: Arrange git repository
        run: |
          git config user.name "Heroku-Deploy"
          git config user.email "kmhapinn3@gmail.com"
          git fetch --prune --unshallow
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          echo 'web: bin/start-nginx-debug npm start' > Procfile
          curl https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem > config/amazon-rds-ca-cert.pem
          git add -A && git commit -m "Added Procfile & Amazon RDS CA Certificate"
      - name: Deploy backend to Heroku
        run: git push heroku main:refs/heads/main --force

      ## ssh deployment
      # - name: SSH and deploy app
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd ~/forum-api
      #       git pull origin main
      #       npm install
      #       npm run migrate up
      #       pm2 restart forum-api
